#!/usr/bin/env bash
# Full project setup: check prerequisites, generate .env, install Python deps.
#
# Usage: ./scripts/setup.sh
#
# This script is safe to re-run. It will not overwrite an existing .env file
# unless you pass --force.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
ENV_FILE="$PROJECT_DIR/.env"
FORCE=false

for arg in "$@"; do
    [[ "$arg" == "--force" ]] && FORCE=true
done

echo "=== API Gateway Manager - Project Setup ==="
echo ""

# ---- 1. Check prerequisites ----
echo "--- Checking prerequisites ---"

check_cmd() {
    if command -v "$1" &>/dev/null; then
        echo "  [OK] $1 ($($1 --version 2>&1 | head -1))"
        return 0
    else
        echo "  [MISSING] $1 -- $2"
        return 1
    fi
}

MISSING=0
check_cmd python3 "Install Python 3.11+: https://python.org" || MISSING=1
check_cmd pip "Comes with Python" || MISSING=1
check_cmd gcloud "Install: https://cloud.google.com/sdk/docs/install" || MISSING=1

if [[ $MISSING -eq 1 ]]; then
    echo ""
    echo "Install missing prerequisites and re-run this script."
    exit 1
fi

# Check Python version
PY_VERSION=$(python3 -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")')
PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)
if [[ "$PY_MAJOR" -lt 3 ]] || [[ "$PY_MAJOR" -eq 3 && "$PY_MINOR" -lt 11 ]]; then
    echo "  [WARN] Python $PY_VERSION detected. Python 3.11+ recommended."
fi

echo ""

# ---- 2. Check gcloud auth ----
echo "--- Checking gcloud authentication ---"

GCLOUD_ACCOUNT=$(gcloud config get account 2>/dev/null || true)
if [[ -z "$GCLOUD_ACCOUNT" ]]; then
    echo "  [WARN] Not authenticated. Run: gcloud auth login"
    echo "  Then: gcloud auth application-default login"
else
    echo "  [OK] Authenticated as: $GCLOUD_ACCOUNT"
fi

# Get current project
GCLOUD_PROJECT=$(gcloud config get project 2>/dev/null || true)
echo ""

# ---- 3. Detect GCP values ----
echo "--- Detecting GCP configuration ---"

# Project ID: prefer env var > gcloud config > default
if [[ -n "${GCP_PROJECT_ID:-}" ]]; then
    PROJECT_ID="$GCP_PROJECT_ID"
    echo "  Project ID (from env): $PROJECT_ID"
elif [[ -n "$GCLOUD_PROJECT" ]]; then
    PROJECT_ID="$GCLOUD_PROJECT"
    echo "  Project ID (from gcloud): $PROJECT_ID"
else
    PROJECT_ID="mestrealvaro"
    echo "  Project ID (default): $PROJECT_ID"
fi

# Region
GCP_REGION="${GCP_REGION:-us-central1}"
echo "  Region: $GCP_REGION"

# Detect existing service accounts
PROXY_SA=""
PROXY_SA_EMAIL="vertex-proxy-sa@${PROJECT_ID}.iam.gserviceaccount.com"
if gcloud iam service-accounts describe "$PROXY_SA_EMAIL" --project="$PROJECT_ID" &>/dev/null 2>&1; then
    PROXY_SA="$PROXY_SA_EMAIL"
    echo "  Proxy SA (detected): $PROXY_SA"
else
    echo "  Proxy SA: not found (run scripts/create-service-account.sh)"
fi

# Detect existing Vertex AI endpoints
echo "  Checking Vertex AI endpoints ..."
VERTEX_ENDPOINT_ID=""
ENDPOINTS_JSON=$(gcloud ai endpoints list \
    --project="$PROJECT_ID" \
    --region="$GCP_REGION" \
    --format="json(name,displayName)" 2>/dev/null || echo "[]")
ENDPOINT_COUNT=$(echo "$ENDPOINTS_JSON" | python3 -c "import json,sys; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")

if [[ "$ENDPOINT_COUNT" -gt 0 ]]; then
    echo "  Found $ENDPOINT_COUNT Vertex AI endpoint(s):"
    echo "$ENDPOINTS_JSON" | python3 -c "
import json, sys
for ep in json.load(sys.stdin):
    name = ep.get('name','')
    eid = name.split('/')[-1] if '/' in name else name
    display = ep.get('displayName','')
    print(f'    {eid}  ({display})')
" 2>/dev/null
    # Use the first one as default
    VERTEX_ENDPOINT_ID=$(echo "$ENDPOINTS_JSON" | python3 -c "
import json, sys
eps = json.load(sys.stdin)
if eps:
    name = eps[0].get('name','')
    print(name.split('/')[-1] if '/' in name else name)
" 2>/dev/null || echo "")
else
    echo "  No Vertex AI endpoints found in $GCP_REGION"
    echo "  (Leave VERTEX_AI_ENDPOINT_ID empty if using publisher models like Gemini)"
fi

echo ""

# ---- 4. Generate .env ----
echo "--- Generating .env ---"

if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo "  .env already exists. Use --force to overwrite."
    echo "  Skipping .env generation."
else
    cat > "$ENV_FILE" << EOF
# === API Gateway Manager Configuration ===
# Generated by scripts/setup.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

# GCP Project
GCP_PROJECT_ID=$PROJECT_ID
GCP_REGION=$GCP_REGION

# App Server
HOST=0.0.0.0
PORT=8081
LOG_LEVEL=INFO

# API Gateway
# Set after creating an API with the web UI or gcloud
GATEWAY_API_ID=
GATEWAY_REGION=$GCP_REGION

# Cloud Run Proxy
PROXY_SERVICE_NAME=vertex-ai-proxy
PROXY_SERVICE_ACCOUNT=$PROXY_SA

# Vertex AI
# For custom endpoints: set the numeric endpoint ID
# For Generative AI (Gemini): leave empty, use publisher models via the UI
VERTEX_AI_ENDPOINT_ID=$VERTEX_ENDPOINT_ID
VERTEX_AI_REGION=$GCP_REGION

# Vertex AI Model (for Generative AI / Gemini)
# Examples: gemini-2.0-flash, gemini-2.5-pro, gemini-2.5-flash
VERTEX_AI_MODEL=gemini-2.0-flash
EOF
    echo "  Written: $ENV_FILE"
fi

echo ""

# ---- 5. Install Python deps ----
echo "--- Installing Python dependencies ---"
pip install -r "$PROJECT_DIR/requirements.txt" --quiet 2>&1 | tail -3
echo "  Done."
echo ""

# ---- 6. Summary ----
echo "=== Setup Complete ==="
echo ""
echo "Next steps:"
echo "  1. Review .env and fill in any missing values"
echo "  2. Enable GCP APIs:     ./scripts/enable-gcp-apis.sh $PROJECT_ID"
echo "  3. Create service accounts: ./scripts/create-service-account.sh $PROJECT_ID"
echo "  4. Run the app:         uvicorn app.main:app --host 0.0.0.0 --port 8081 --reload"
echo "  5. Open:                http://localhost:8081"
echo ""
echo "Vertex AI Discovery Document reference:"
echo "  https://aiplatform.googleapis.com/\$discovery/rest?version=v1"
echo ""
echo "Key API patterns (from Discovery Document):"
echo "  Custom endpoints:  POST .../endpoints/{id}:predict"
echo "  Generative AI:     POST .../publishers/google/models/{model}:generateContent"
echo "  Streaming:         POST .../publishers/google/models/{model}:streamGenerateContent"
echo "  Token counting:    POST .../publishers/google/models/{model}:countTokens"
